# Generated by Django 2.2.2 on 2019-06-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='qtype',
        ),
        migrations.AlterField(
            model_name='questionset',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
